---
# task/main file for update_motd
- name: "Import prerequisites.yml"
  ansible.builtin.include_tasks: prerequisites.yml

- name: "Import install.yml"
  ansible.builtin.include_tasks: install.yml

- name: "Import cleanup.yml"
  ansible.builtin.include_tasks: cleanup.yml

- name: "Import configure.yml"
  ansible.builtin.include_tasks: configure.yml
